---
# tasks file for ansible-role-squid

- name: load distribution specific vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - squid
    - setup
    - install

- block:

    - name: install
      apt:
        name: "{{ squid_dependencies + squid_pkg is string | ternary([squid_pkg], squid_pkg) }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
        install_recommends: false
      tags:
        - install

    - name: setup
      template:
        src: squid.conf.j2
        dest: "{{ squid_root }}/squid.conf"
        validate: "{{ squid_service }} -k parse -f %s"
      notify: squid reload
      tags:
        - setup

  become: true
  tags:
    - squid
